// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0FQ-3omtKyIpYNhnK7gVjUKG4wDv1rM',
    appId: '1:736028541928:web:1cbea5a456e598703eda5d',
    messagingSenderId: '736028541928',
    projectId: 'fruit-hub-7f20e',
    authDomain: 'fruit-hub-7f20e.firebaseapp.com',
    storageBucket: 'fruit-hub-7f20e.firebasestorage.app',
    measurementId: 'G-GR3F88LE75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6V0qg7gkNrCOl63MWHmb7lkMUfBMnqwQ',
    appId: '1:736028541928:android:1bae2b7e3bb425243eda5d',
    messagingSenderId: '736028541928',
    projectId: 'fruit-hub-7f20e',
    storageBucket: 'fruit-hub-7f20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzVheVNXEyGq-s62wf7STE4gZ4TibhPA8',
    appId: '1:736028541928:ios:d32fe27267b3784a3eda5d',
    messagingSenderId: '736028541928',
    projectId: 'fruit-hub-7f20e',
    storageBucket: 'fruit-hub-7f20e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzVheVNXEyGq-s62wf7STE4gZ4TibhPA8',
    appId: '1:736028541928:ios:d32fe27267b3784a3eda5d',
    messagingSenderId: '736028541928',
    projectId: 'fruit-hub-7f20e',
    storageBucket: 'fruit-hub-7f20e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB0FQ-3omtKyIpYNhnK7gVjUKG4wDv1rM',
    appId: '1:736028541928:web:39892c386471cd643eda5d',
    messagingSenderId: '736028541928',
    projectId: 'fruit-hub-7f20e',
    authDomain: 'fruit-hub-7f20e.firebaseapp.com',
    storageBucket: 'fruit-hub-7f20e.firebasestorage.app',
    measurementId: 'G-193PTBWZW2',
  );
}
